service: hustle-hub
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: production

functions:
  user:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true


# plugins:
#   - serverless-offline